### ISSUE TITLE
Not working on all posts page for a user

### ISSUE THREAD

**Issue by Kakifrucht** [noriods/automore#1]
Tested on Chrome, Firefox and Edge. It works fine in Chrome, but not in Firefox/Edge. More posts aren't loaded automatically and there is no button to click either. Other than this the extension works normally on all other pages.

**Comment by noriods** [comment]
Thanks @Kakifrucht. I'm on Mac so I can't test Edge but I'll install Firefox and check there.

Can you [record a video](https://www.useloom.com/) of what it does in Edge?

**Comment by noriods** [comment]
@Kakifrucht I tested it on Firefox on Mac and it works. Is your forum live? Testing on your forum where you experience the issue will help me debug it.

**Comment by noriods** [comment]
Also would you mind testing it on Firefox and Edge on *my* forum?

https://community.guitartalk.co.za/

If the problem isn't there, then we can at least confirm that it arises out of a conflict between the extension and something on your forum.

**Comment by Kakifrucht** [comment]
Very oddly, I cannot reproduce this on your forum anymore (I was able to do so yesterday though). I can however still reproduce it on my live forum [here](https://halfminer.de/forum/u/Kakifrucht). It only works for discussion list, not for posts or mentions.

[Video of it in action](https://i.imgur.com/RuHPyYO.gifv).

Edit: Turns out it also happens on Chrome, while not logged into the forum. Logged in it works, even in Firefox/Edge.

**Comment by noriods** [comment]
@Kakifrucht can you disable the auto-more extension and see if the button still shows? And if it shows, please click it and let me know what happens. I think this is unrelated to the extension and this would be a good way to confirm (or debunk) that theory.

**Comment by noriods** [comment]
By the way, thanks for the video. Also your forum looks great!

**Comment by Kakifrucht** [comment]
Your guess was correct, it is unrelated to Auto More. Turns out that some profiles simply don't show the button when logged out. I can reproduce this on discuss.flarum.org on Toby's profile aswell (while logged out).

Thanks for helping out!

**Comment by noriods** [comment]
Glad I could help!
