### ISSUE TITLE
Need compatibility with Flarum Beta 14

### ISSUE THREAD

**Issue by PeopleInside** [noriods/automore#3]
Hi, this extension need an update for the Beta 14 version of Flarum :D

**Comment by noriods** [comment]
I'm accepting PRs ;) Right now I can't do it myself.

**Comment by PeopleInside** [comment]
Thanks, I think I cannot help in this as I don't know what to do.
I love this extension and hope will be not abandoned, if yes can be maybe passed to Friend of Flarum.
I will try to wait as I cannot yet update to Beta 14 seems there are few issues.

Sorry to hear you are busy, best luck.

**Comment by noriods** [comment]
Sweet, thanks 😄

**Comment by Nearata** [comment]
Tested as is on beta 14 and works fine

**Comment by noriods** [comment]
Ah nice, thanks for that!
